### ISSUE TITLE
Human-readable results output

### ISSUE THREAD

**Issue by pscicluna** [ICSM/pgmuvi#8]
pgmuvi should create an output table so that people can understand what the results are and what they mean. 

This might involve two separate implementations for MAP and MCMC solutions, as credible intervals need to be reported in the latter case.

**Comment by pscicluna** [comment]
Partial solution for 1D lightcurves in https://github.com/ICSM/pgmuvi/pull/22

**Comment by pscicluna** [comment]
Testing on a 2D lightcurve results in the following error:
```
Traceback (most recent call last):
  File "/home/psciclun/Downloads/light curves-20221213T145300Z-001/light curves/pgmuvi2Dtest.py", line 42, in <module>
    lightcurve_2d.print_results()
  File "/home/psciclun/code/pythondev/pgmuvi/pgmuvi/lightcurve.py", line 395, in print_results
    print(f"{key}: {results_tmp[:,0].flatten()}, {results_tmp[:,1].flatten()}")
IndexError: index 1 is out of bounds for axis 1 with size 1 
```
We will have to figure out what shape the results are in for each variable in 2D. It did successfully output the loss, delta loss, likelihood.noise_covar.raw_noise, mean_module.constant, and covar_module.raw_mixture_weights, which as expected are all 1D. It couldn't output the mixture means or sigmas.
